### PR TITLE
Metric Exporter: NOT DONE

### PR DESCRIPTION
**Pull request by davidwitten**
### Note
This includes other commits, for a more accurate look at my edits, check [**here**](https://github.com/open-telemetry/opentelemetry-js/compare/master...davidwitten:master).

### Current Work
This is unfinished, it's just a way to follow my work easier. I'm still actively changing many things. 

A few things I'm thinking about/working on now
- CollectorTraceExporter and CollectorMetricExporter are extremely similar. How can I reuse code better?
One issue is they inherit from different classes (SpanExporter and MetricExporter, respectively). I could just make helper functions though

- Adding better metric testing (This is very unfinished right now)
- Add an example code segment and better documentation

### CODE REVIEW

**Comment by davidwitten** [comment]
Bummer, not all of these commits are mine. I merged my code with the upstream repo. This shouldn't be an issue when I push my PR to the main repo.

**Comment by davidwitten** [comment]
@JorrieB Couldn't put you as a reviewer

**Comment by JorrieB** [comment]
> @JorrieB Couldn't put you as a reviewer

Ain't no thang, I'll take a look now and we'll figure out permissions another day.

**Review by tinylox — COMMENTED** [review]
Is this a mix of your code and also upstream changes ? I've synced our repo with the upstream and you pull down our changes it should clear itself up.

**Comment by tinylox** [comment]
Also can you take these changes and place them onto a new branch rather than work on master directly? It will make it easier to keep our master clean and in sync with the upstream project and we will submit our work through branches.

**Comment by davidwitten** [comment]
I have my own repo, so I've just been coding on that. Also I just made a new PR.

**Pull request closed without merging**
